services:

  n8n:

    image: n8nio/n8n

    container_name: monitor-precos-n8n

    restart: unless-stopped

    ports:
      - "5680:5678"

    volumes:
      - ./data:/home/node/.n8n

    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo